### ISSUE TITLE
Trouble linking

### ISSUE THREAD

**Issue by zaydek** [jgthms/minireset.css#13]
Am I an idiot? I'm having trouble linking this like this:

```
<link rel="stylesheet" href="https://raw.githubusercontent.com/jgthms/minireset.css/master/minireset.css">
```

But works when I download and import locally. 🙉

**Comment by mpoonuru** [comment]
You Can't link this way.

**Comment by 100Errors** [comment]
Hey,
you can't do this because githubusercontent sends the "wrong" headers, please check out https://rawgit.com in your case, you could use https://cdn.rawgit.com/jgthms/minireset.css/a0190527/minireset.min.css
