### ISSUE TITLE
Block fix

### ISSUE THREAD

**Issue by ZAYDEK** [jgthms/minireset.css#14]
Copying code from Bulma: https://github.com/jgthms/bulma/blob/master/css/bulma.css#L312. Shouldn't minireset.css include a precaution for HTML5 elements for older browsers?

```
article,
aside,
figure,
footer,
header,
hgroup,
section {
  display: block;
}
```

Seems like it should be the second rule, beneath
```
... {
  margin: 0;
  padding: 0;
}
```

**Comment by jgthms** [comment]
That's for browers that are at least 8 years old.
