### ISSUE TITLE
[img] display: block

### ISSUE THREAD

**Issue by lukasoppermann** [jgthms/minireset.css#2]
Hey,

how about adding this, to avoid the unwanted, very weird space below images. Or is this issue already covered with something else?

``` php
img{
    display: block; /* avoids space at bottom */
}
```

**Comment by thomasdigby** [comment]
I think this issue can be avoided with any `vertical-align` property, try `vertical-align: middle;`.

**Comment by lukasoppermann** [comment]
But I still think something like this should be included. Anything that removes this weird issue is fine.

**Comment by jgthms** [comment]
Having `img { display: block;}` is way too opinionated, and will cause lots of problems. Images are considered inline content, although they have a width and a height.

Adding a `vertical-align: top` could be possible, but trigger other problems.

**Comment by lukasoppermann** [comment]
Hmm, I do understand that `img { display: block;}` is to opinionated, but I feel providing an out of the box solution, whatever you would choose for it, would be good.

**Comment by thomasdigby** [comment]
Harry Roberts uses a `vertical-align` in his discovr repo, I think it's fairly safe to use in this context.   https://github.com/thomasdigby/discovr/blob/master/css/elements/_elements.images.scss

**Comment by jgthms** [comment]
`vertical-align: middle` is not a good option as it breaks the natural flow of a paragraph of text:

<img width="240" alt="screen shot 2016-09-11 at 22 18 11" src="https://cloud.githubusercontent.com/assets/1254808/18420594/e8a21ef6-786d-11e6-956b-1c4b86a1bac9.png">

The only options that would both remove the space at the bottom _and_ leave an image readable in a block of text are:

```css
vertical-align: sub;
vertical-align: text-bottom;
vertical-align: bottom;
```

Not sure what option is the best.

**Comment by thomasdigby** [comment]
`vertical-align: text-bottom` might be the closest match to the default `baseline` property without rendering the space underneath. https://developer.mozilla.org/en/docs/Web/CSS/vertical-align

**Comment by jgthms** [comment]
Looks like a good candidate.

**Comment by lukasoppermann** [comment]
@jgthms could you implement it or would you accept a PR?
