### ISSUE TITLE
Question about UL and OL

### ISSUE THREAD

**Issue by ZAYDEK** [jgthms/minireset.css#23]
Hey @jgthms, I hope you’re well.

I’m just wondering what the decisioning was for

```
ul {
  list-style: none;
}
```

But omitting `ol` from `list-style: none`?

Thanks.

**Comment by jgthms** [comment]
`ol` has automatic numbering which is quite useful. I removed the dots  `ul` because these lists can be used for semantic reasons, in a nav for example, but you don’t necessarily want the default styling.

**Comment by dezertdezine** [comment]
`ol` wasn't showing numbers for me. I had to add:

`ol li {
  list-style-position: inside;
}`
