### ISSUE TITLE
Minireset conflict with custom styles

### ISSUE THREAD

**Issue by daniel-navas** [jgthms/minireset.css#26]
https://github.com/jgthms/minireset.css/blob/66b8b83c991933cb0fb16c897f3d427990509555/minireset.sass#L78

I'm using a simple rule:
```
td
  text-align: center
```

since the rule in the minireset is more specific, it take precedence over mine.

I can easily solve this by modifing the minireset, but then what is the idea of using the minireset. I could use my own version, but the truth is that I dont even know what does the line that I removed.

This is an issue and a question...

What `&:not([align]) ` does? I couldn't find anything on the web (I mean like, what exactly does?)

**Comment by abellion** [comment]
I have the same issue, this rule takes precedence over mine. It looks like `align` is an old attribut, deprecated in HTML5 : https://www.w3.org/TR/2010/WD-html-markup-20100624/td.html

> The align attribute on the td element is obsolete. Use CSS instead.

**Comment by jgthms** [comment]
Actually, I'm just gonna remove the `align` rule completely. Thanks for your help.
